[package]
name = "roguelike"
version = "0.1.0"
authors = ["aschuhardt"]
build = "build.rs"

[dependencies]
ggez = "0.3.2"
lazy_static = "0.2.8"
rand = "0.3.15"
mopa = "0.2.2"
uuid = { version = "*", features = ["serde", "v4"] }
serde = "^1.0"
serde_derive = "1.0.8"
bincode = "0.8.0"